### ISSUE TITLE
Need a straightforward installation process.

### ISSUE THREAD

**Issue by edsgerlin** [skx/templer#21]
* It is hard to install Templer on Windows.
* I wish I could install Templer simply via CPAN.

**Comment by b3** [comment]
The migration to using CPAN process has allow to clean the code a lot.
Unfortunately it implied that the generated script (`bin/templer`) can not be used as a standalone script anymore. In order for the script to work now we need the differents `Templer::` modules to be accessible via perl outside the script itself and thus they need to be installed somewhere in `PERLLIB` directories.

So now we cannot just dropped it in a directory and use it as is.

**Comment by b3** [comment]
A "*standalone*" script can easily be build by some Unix shell commands:

    cat $(find lib -type f |grep -v 'Templer/Site/New') bin/templer >bin/templer-standalone
    sed -i -e '1i\#!/usr/bin/perl' -e '/^require.*Templer/ d' bin/templer-standalone
    chmod +x bin/templer-standalone

I am sure that this is not the cleanest way (it depends on shell and should be a trouble on other systems) but that meets my needs for now.

I however do not know how to add it a clean way in the distribution (some extra `Makefile` target maybe), nor do I know if it you should add the complete "*standalone*" script feature back into it.

I just ask.

**Comment by skx** [comment]
For the moment I've hacked up a simple thing, much along the lines of your version.  As you say it's a bit nasty, but the following should do the job:

     perl Makefile.PL ; make standalone

Once you run that you'll have `./templer` which is standalone.  However the module collision means that `./templer --help` will show a lot of rubbish before the real output.  I will see if I can improve things before a new release, but I'll commit this just now as an interim step.
